config/routes.rb
Rails.application.routes.draw do

  resources :players
  resources :games
  resources :tournaments
  resources :practices
  resources :teams

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :tournament
  belongs_to :team
end

app/models/gamestat.rb
class Gamestat < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
end

app/models/player.rb
class Player < ActiveRecord::Base
      validates :name, presence: { message: "入力してください"}
end

app/models/practice.rb
class Practice < ActiveRecord::Base
    validates :name, presence: { message: "入力してください"}
end

app/models/practicestat.rb
class Practicestat < ActiveRecord::Base
  belongs_to :practice
  belongs_to :player
end

app/models/round.rb
class Round < ActiveRecord::Base
      validates :name, presence: { message: "入力してください"}
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates :name, presence: { message: "入力してください"}
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
      validates :name, presence: { message: "入力してください"}
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
end

app/controllers/gamestats_controller.rb
class GamestatsController < ApplicationController
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.all
    @gamestats = Gamestat.all
  end

  def new
    @player = Player.new
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if  @player.update(player_params)
      redirect_to players_path
    else
      render 'edit'
    end
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to  players_path
    else
      render 'new'
    end
  end

private

  def player_params
    params[:player].permit(:name)
  end

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    if  @team.update(team_params)
      redirect_to teams_path
    else
      render 'edit'
    end
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to  teams_path
    else
      render 'new'
    end
  end

private

  def team_params
    params[:team].permit(:name)
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController

  def index
    @tournaments = Tournament.all
  end

  def new
    @tournament = Tournament.new
  end

  def edit
    @tournament = Tournament.find(params[:id])
  end

  def update
    @tournament = Tournament.find(params[:id])
    if  @tournament.update(tournament_params)
      redirect_to tournaments_path
    else
      render 'edit'
    end
  end

  def create
    @tournament = Tournament.new(tournament_params)
    if @tournament.save
      redirect_to  tournaments_path
    else
      render 'new'
    end
  end

private

  def tournament_params
    params[:tournament].permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/gamestats_helper.rb
module GamestatsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/practicestats_helper.rb
module PracticestatsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/edit.html.erb
<!--ナビバーの設定-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">

    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="">GameStatistics.info</a>
  </div>

  <div class="collapse navbar-collapse target">

    <ul class="nav navbar-nav">
      <li ><%= link_to "Game", games_path %></li>
      <li ><%= link_to "Player", players_path %></li>
      <li class="active"><%= link_to "Tournament", tournaments_path %></li>
      <li ><%= link_to "Practice", practices_path %></li>
      <li ><%= link_to "Team", teams_path %></li>

    </ul>

  </div>
</nav>


<!--表-->
<div class="container" style="padding:60px 0">
  <%= form_for @tournament do |f| %>
    <p>
      <%= f.label :"Edit tournament Name" %><br>
      <%= f.text_field :name %>
      <% if @tournament.errors.any? %>
      <%= @tournament.errors.messages[:name][0] %>
      <% end %>

    </p>

    <p>
      <%= f.submit class: "btn btn-primary"%>
    </p>

  <% end %>

</div>

app/views/tournaments/index.html.erb
<!--ナビバーの設定-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">

    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="/">GameStatistics.info</a>
  </div>

  <div class="collapse navbar-collapse target">

    <ul class="nav navbar-nav">
      <li ><%= link_to "Game", games_path %></li>
      <li ><%= link_to "Player", players_path %></li>
      <li class="active"><%= link_to "Tournament", tournaments_path %></li>
      <li ><%= link_to "Practice", practices_path %></li>
      <li ><%= link_to "Team", teams_path %></li>

    </ul>

  </div>
</nav>


<!--表-->
<div class="container" style="padding:60px 0">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">全大会</div>

    <!-- Table -->
    <table class="table table-striped table-bordered table-hover table-condensed">
      <thead>
        <tr><th>大会リスト</th></tr>
      </thead>
      <tbody>

        <% @tournaments.each do |tournament| %>
          <tr><td><%= link_to tournament.name, edit_tournament_path(tournament.id) %></td></tr>
        <% end %>
      </tbody>
    </table>

  </div>
    <%= link_to "追加", new_tournament_path , class: "btn btn-primary" %>
</div>

app/views/tournaments/new.html.erb
<!--ナビバーの設定-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">

    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="">GameStatistics.info</a>
  </div>

  <div class="collapse navbar-collapse target">

    <ul class="nav navbar-nav">
      <li ><%= link_to "Game", games_path %></li>
      <li ><%= link_to "Player", players_path %></li>
      <li class="active"><%= link_to "Tournament", tournaments_path %></li>
      <li ><%= link_to "Practice", practices_path %></li>
      <li ><%= link_to "Team", teams_path %></li>

    </ul>

  </div>
</nav>


<!--表-->
<div class="container" style="padding:60px 0">
  <%= form_for @tournament do |f| %>
    <p>
      <%= f.label :"Add tournament Name" %><br>
      <%= f.text_field :name %>
      <% if @tournament.errors.any? %>
      <%= @tournament.errors.messages[:name][0] %>
      <% end %>

    </p>

    <p>
      <%= f.submit class: "btn btn-primary"%>
    </p>

  <% end %>

</div>