config/routes.rb
Rails.application.routes.draw do

  resources :players
  resources :games
  resources :tournaments
  resources :practices
  resources :teams

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :tournament
  belongs_to :team
end

app/models/gamestat.rb
class Gamestat < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
end

app/models/player.rb
class Player < ActiveRecord::Base
      validates :name, presence: { message: "入力してください"}
end

app/models/practice.rb
class Practice < ActiveRecord::Base
    validates :name, presence: { message: "入力してください"}
end

app/models/practicestat.rb
class Practicestat < ActiveRecord::Base
  belongs_to :practice
  belongs_to :player
end

app/models/round.rb
class Round < ActiveRecord::Base
      validates :name, presence: { message: "入力してください"}
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates :name, presence: { message: "入力してください"}
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
      validates :name, presence: { message: "入力してください"}
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
end

app/controllers/gamestats_controller.rb
class GamestatsController < ApplicationController
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.all
    @gamestats = Gamestat.all
  end

  def new
    @player = Player.new
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if  @player.update(player_params)
      redirect_to players_path
    else
      render 'edit'
    end
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to  players_path
    else
      render 'new'
    end
  end

private

  def player_params
    params[:player].permit(:name)
  end

end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController

  def index
    @practices = Practice.all
  end

  def new
    @practice = Practice.new
  end

  def edit
    @practice = Practice.find(params[:id])
  end

  def update
    @practice = Practice.find(params[:id])
    if  @practice.update(practice_params)
      redirect_to practices_path
    else
      render 'edit'
    end
  end

  def create
    @practice = Practice.new(practice_params)
    if @practice.save
      redirect_to  practices_path
    else
      render 'new'
    end
  end

private

  def practice_params
    params[:practice].permit(:name)
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    if  @team.update(team_params)
      redirect_to teams_path
    else
      render 'edit'
    end
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to  teams_path
    else
      render 'new'
    end
  end

private

  def team_params
    params[:team].permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/gamestats_helper.rb
module GamestatsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/practicestats_helper.rb
module PracticestatsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/games/index.html.erb
<!--ナビバーの設定-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">

    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="">GameStatistics.info</a>
  </div>

  <div class="collapse navbar-collapse target">

    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Game", games_path %></li>
      <li ><%= link_to "Player", players_path %></li>
      <li ><%= link_to "Tournament", tournaments_path %></li>
      <li ><%= link_to "Practice", practices_path %></li>
      <li ><%= link_to "Team", teams_path %></li>

    </ul>

  </div>
</nav>


<!--表-->
<div class="container" style="padding:60px 0">

  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">全試合</div>

    <!-- Table -->
    <table class="table table-striped table-bordered table-hover table-condensed">
      <thead>
        <tr><th>試合</th><th>大会</th><th>スコア</th></tr>
      </thead>
      <tbody>
        <tr><td><%= link_to "立川 vs 国立", players_path %></td><td>2015国公立大会</td><td>12-2</td></tr>
        <tr><td><%= link_to "立川 vs 東大和", players_path %></td><td>2015国公立大会</td><td>12-2</td></tr>
        <tr><td><%= link_to "立川 vs 府中", players_path %></td><td>2015国公立大会</td><td>12-2</td></tr>
      </tbody>
    </table>

  </div>

</div>

app/views/players/edit.html.erb
<!--ナビバーの設定-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">

    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="">GameStatistics.info</a>
  </div>

  <div class="collapse navbar-collapse target">

    <ul class="nav navbar-nav">
      <li ><%= link_to "Game", games_path %></li>
      <li class="active"><%= link_to "Player", players_path %></li>
      <li ><%= link_to "Tournament", tournaments_path %></li>
      <li ><%= link_to "Practice", practices_path %></li>
      <li ><%= link_to "Team", teams_path %></li>

    </ul>

  </div>
</nav>


<!--表-->
<div class="container" style="padding:60px 0">
  <%= form_for @player do |f| %>
    <p>
      <%= f.label :"Edit player Name" %><br>
      <%= f.text_field :name %>
      <% if @player.errors.any? %>
      <%= @player.errors.messages[:name][0] %>
      <% end %>

    </p>

    <p>
      <%= f.submit class: "btn btn-primary"%>
    </p>

  <% end %>

</div>

app/views/players/index.html.erb
<!--ナビバーの設定-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">

    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="/">GameStatistics.info</a>
  </div>

  <div class="collapse navbar-collapse target">

    <ul class="nav navbar-nav">
      <li ><%= link_to "Game", games_path %></li>
      <li class="active"><%= link_to "Player", players_path %></li>
      <li ><%= link_to "Tournament", tournaments_path %></li>
      <li ><%= link_to "Practice", practices_path %></li>
      <li ><%= link_to "Team", teams_path %></li>

    </ul>

  </div>
</nav>


<!--表-->
<div class="container" style="padding:60px 0">

  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">全選手記録</div>


  <table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
      <tr><th>Name</th><th>G/S</th><th>%</th><th>6m</th><th>Wing</th> <th>9m</th> <th>7m</th> <th>FB</th> <th>BT</th> <th>AS</th> <th>TF</th> <th>ST</th> <th>BS</th> <th>YC</th> <th>2Min</th> <th>RC</th> <th>DR</th></tr>
    </thead>
    <tbody>

      <% @players.each do |player| %>
      <tr><td><%= player.name %></td>
        <% @total_sixm_g = 0 %>
        <% @total_sixm_n = 0 %>
        <% @total_wing_g = 0 %>
        <% @total_wing_n = 0 %>
        <% @total_ninem_g = 0 %>
        <% @total_ninem_n = 0 %>
        <% @total_sevenm_g = 0 %>
        <% @total_sevenm_n = 0 %>
        <% @total_sevenm_g = 0 %>
        <% @total_sevenm_n = 0 %>
        <% @total_FB_g = 0 %>
        <% @total_FB_n = 0 %>
        <% @total_BT_g = 0 %>
        <% @total_BT_n = 0 %>
        <% @total_AS_n = 0 %>
        <% @total_TF_n = 0 %>
        <% @total_ST_n = 0 %>
        <% @total_BS_n = 0 %>
        <% @total_YC_n = 0 %>
        <% @total_twoMin_n = 0 %>
        <% @total_RC_n = 0 %>
        <% @total_DR_n = 0 %>
        <% @total_goal = 0 %>
        <% @total_shoot = 0 %>
        <% @gamestats.each do |gamestat| %>
          <% if gamestat.player_id == player.id %>
            <% @total_sixm_g = gamestat.sixm_g %>
            <% @total_sixm_n = gamestat.sixm_n %>
            <% @total_wing_g = gamestat.wing_g %>
            <% @total_wing_n = gamestat.wing_n %>
            <% @total_ninem_g = gamestat.ninem_g %>
            <% @total_ninem_n = gamestat.ninem_n %>
            <% @total_sevenm_g = gamestat.sevenm_g %>
            <% @total_sevenm_n = gamestat.sevenm_n %>
            <% @total_FB_g = gamestat.FB_g %>
            <% @total_FB_n = gamestat.FB_n %>
            <% @total_BT_g = gamestat.BT_g %>
            <% @total_BT_n = gamestat.BT_n %>
            <% @total_AS_n = gamestat.AS_n %>
            <% @total_TF_n = gamestat.TF_n %>
            <% @total_ST_n = gamestat.ST_n %>
            <% @total_BS_n = gamestat.BS_n %>
            <% @total_YC_n = gamestat.YC_n %>
            <% @total_twoMin_n = gamestat.twoMin_n %>
            <% @total_RC_n = gamestat.RC_n %>
            <% @total_DR_n = gamestat.DR_n %>
            <% @total_goal = gamestat.sixm_g + gamestat.wing_g + gamestat.ninem_g+gamestat.sevenm_g+gamestat.FB_g+ gamestat.BT_g %>
            <% @total_shoot =  gamestat.sixm_g + gamestat.sixm_n + gamestat.wing_g + gamestat.wing_n + gamestat.ninem_g + gamestat.ninem_n + gamestat.sevenm_g + gamestat.sevenm_n + gamestat.FB_g + gamestat.FB_n + gamestat.BT_g + gamestat.BT_n %>
          <% end %>
        <% end %>
        <td><%= @total_goal %>/<%= @total_shoot %></td>
        <td><%= (@total_goal.to_f/@total_shoot.to_f * 100).round(2) %> % </td>
        <td><%=  @total_sixm_g %>/<%=  @total_sixm_g+  @total_sixm_n %></td>
        <td><%=  @total_wing_g %>/<%=  @total_wing_g+  @total_wing_n %></td>
        <td><%=  @total_ninem_g %>/<%=  @total_ninem_g+  @total_ninem_n %></td>
        <td><%=  @total_sevenm_g %>/<%=  @total_sevenm_g+  @total_sevenm_n %></td>
        <td><%=  @total_FB_g %>/<%=  @total_FB_g+  @total_FB_n %></td>
        <td><%=  @total_BT_g %>/<%=  @total_BT_g + @total_BT_n %></td>
        <td><%=  @total_AS_n %></td>
        <td><%=  @total_TF_n %></td>
        <td><%=  @total_ST_n %></td>
        <td><%=  @total_BS_n %></td>
        <td><%=  @total_YC_n %></td>
        <td><%=  @total_twoMin_n %></td>
        <td><%=  @total_RC_n %></td>
        <td><%=  @total_DR_n %></td>
        </tr>

      <% end %>

    </tbody>
  </table>
</div>
    <%= link_to "追加", new_player_path , class: "btn btn-primary" %>
</div>
</div>

app/views/players/new.html.erb
<!--ナビバーの設定-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">

    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="">GameStatistics.info</a>
  </div>

  <div class="collapse navbar-collapse target">

    <ul class="nav navbar-nav">
      <li ><%= link_to "Game", games_path %></li>
      <li class="active"><%= link_to "Player", players_path %></li>
      <li ><%= link_to "Tournament", tournaments_path %></li>
      <li ><%= link_to "Practice", practices_path %></li>
      <li ><%= link_to "Team", teams_path %></li>

    </ul>

  </div>
</nav>


<!--表-->
<div class="container" style="padding:60px 0">
  <%= form_for @player do |f| %>
    <p>
      <%= f.label :"Add player Name" %><br>
      <%= f.text_field :name %>
      <% if @player.errors.any? %>
      <%= @player.errors.messages[:name][0] %>
      <% end %>

    </p>

    <p>
      <%= f.submit class: "btn btn-primary"%>
    </p>

  <% end %>

</div>

app/views/practices/index.html.erb
<!--ナビバーの設定-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">

    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="/">GameStatistics.info</a>
  </div>

  <div class="collapse navbar-collapse target">

    <ul class="nav navbar-nav">
      <li ><%= link_to "Game", games_path %></li>
      <li ><%= link_to "Player", players_path %></li>
      <li ><%= link_to "Tournament", tournaments_path %></li>
      <li class="active"><%= link_to "Practice", practices_path %></li>
      <li ><%= link_to "Team", teams_path %></li>

    </ul>

  </div>
</nav>


<!--表-->
<div class="container" style="padding:60px 0">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">全練習メニュー</div>

    <!-- Table -->
      <table class="table table-striped table-bordered table-hover table-condensed">
        <thead>
          <tr><th>練習</th></tr>
        </thead>
        <tbody>
          <% @practices.each do |practice| %>
            <tr><td><%= link_to practice.name, edit_practice_path(practice.id) %></td></tr>
          <% end %>
        </tbody>
      </table>

  </div>

  <%= link_to "追加", new_practice_path , class: "btn btn-primary" %>

</div>

app/views/rounds/edit.html.erb
<!--ナビバーの設定-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">

    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="">GameStatistics.info</a>
  </div>

  <div class="collapse navbar-collapse target">

    <ul class="nav navbar-nav">
      <li ><%= link_to "Game", games_path %></li>
      <li ><%= link_to "Player", players_path %></li>
      <li ><%= link_to "Tournament", tournaments_path %></li>
      <li class="active"><%= link_to "Practice", practices_path %></li>
      <li ><%= link_to "Team", teams_path %></li>

    </ul>

  </div>
</nav>


<!--表-->
<div class="container" style="padding:60px 0">
  <%= form_for @practice do |f| %>
    <p>
      <%= f.label :"Edit Practice Name" %><br>
      <%= f.text_field :name %>
      <% if @practice.errors.any? %>
      <%= @practice.errors.messages[:name][0] %>
      <% end %>

    </p>

    <p>
      <%= f.submit class: "btn btn-primary"%>
    </p>

  <% end %>

</div>

app/views/rounds/index.html.erb
<!--ナビバーの設定-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">

    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="/">GameStatistics.info</a>
  </div>

  <div class="collapse navbar-collapse target">

    <ul class="nav navbar-nav">
      <li><a href="">Game</a></li>
      <li class="active"><a href="">Player</a></li>
      <li ><a herf="">Tournament</a></li>
      <li ><a herf="">Practice</a></li>
      <li ><a herf="">Team</a></li>

    </ul>

  </div>
</nav>


<!--表-->
<div class="container" style="padding:60px 0">
  <table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
      <tr><th>Name</th><th>G/S</th><th>%</th><th>6m</th><th>Wing</th> <th>9m</th> <th>7m</th> <th>FB</th> <th>BT</th> <th>AS</th> <th>TF</th> <th>ST</th> <th>BS</th> <th>YC</th> <th>2Min</th> <th>RC</th> <th>DR</th></tr>
    </thead>
    <tbody>
      <% @players.each do |player| %>
      <tr><td><%= player.name %></td><td>200</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rounds/new.html.erb
<!--ナビバーの設定-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">

    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="">GameStatistics.info</a>
  </div>

  <div class="collapse navbar-collapse target">

    <ul class="nav navbar-nav">
      <li ><%= link_to "Game", games_path %></li>
      <li ><%= link_to "Player", players_path %></li>
      <li ><%= link_to "Tournament", tournaments_path %></li>
      <li class="active"><%= link_to "Practice", practices_path %></li>
      <li ><%= link_to "Team", teams_path %></li>

    </ul>

  </div>
</nav>


<!--表-->
<div class="container" style="padding:60px 0">
  <%= form_for @practice do |f| %>
    <p>
      <%= f.label :"Add practice Name" %><br>
      <%= f.text_field :name %>
      <% if @practice.errors.any? %>
      <%= @practice.errors.messages[:name][0] %>
      <% end %>

    </p>

    <p>
      <%= f.submit class: "btn btn-primary"%>
    </p>

  <% end %>

</div>